GET http://localhost:3000/api/courses

### 

POST http://localhost:3000/api/courses

{
    "title": "My course",
    "description": "this is my course",
    "link": "https://somthing.com",
    "level": "beginner"
}

### 

GET http://localhost:3000/api/courses/search?query=react